- hosts: localhost
  connection: local

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:  # Corrected the module name from 'mazon.aws.ec2_instanc' to 'amazon.aws.ec2_instance'
        name: "{{ item.name }}"
        key_name: Devops-POC
        instance_type: t2.micro
        security_group: launch-wizard-1
        region: us-east-2
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"  # Corrected the variable name from 'item.name' to 'item.image'
        tags:
          environment: "{{ item.name }}"

      loop: 
        - { image: "ami-085f9c64a9b75eed5", name: "manage-node1" }
        - { image: "ami-085f9c64a9b75eed5", name: "manage-node2" }
        - { image: "ami-085f9c64a9b75eed5", name: "manage-node3" }
